/**
 * Maps the `guard_ultimo_superadmin` trigger's stable machine code
 * (design.md D5 — `raise exception 'ultimo_superadmin_protegido'`) to a
 * Spanish UI message. The database stays language-neutral; this is the one
 * place that translates it.
 */
export function mapAdminError(error: { message?: string }): string {
  if (error.message?.includes('ultimo_superadmin_protegido')) {
    return 'No se puede eliminar ni degradar al último superadministrador. Debe existir al menos uno.';
  }
  return 'Error al actualizar el administrador.';
}

/**
 * Maps the `configuracion_bancaria` CLABE check constraint violation
 * (design.md Database Design — `check (clabe ~ '^[0-9]{18}$')`) to a Spanish
 * UI message. Matches on the constraint-name substring rather than the full
 * autogenerated name, so it stays robust if Postgres's default naming ever
 * differs from `<table>_<column>_check`.
 */
export function mapBankConfigError(error: { message?: string }): string {
  if (error.message?.includes('clabe_check')) {
    return 'La CLABE debe tener exactamente 18 dígitos numéricos.';
  }
  return 'Error al actualizar la configuración bancaria.';
}
